FROM node:18-alpine
WORKDIR /app

# Install only prod deps
COPY package.json ./
RUN npm install --only=production

COPY src ./src
COPY .env.example ./

ENV PORT=8080
EXPOSE 8080

CMD ["node", "src/server.js"]
